"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var _1_array_1 = require("./exercizio/1-array");
var _2_vocale_conso_1 = require("./exercizio/2-vocale-conso");
var _3_inverse_1 = require("./exercizio/3-inverse");
var _4_pali_1 = require("./exercizio/4-pali");
var _5_factorial_1 = require("./exercizio/5-factorial");
var _6_vectorprod_1 = require("./exercizio/6-vectorprod");
console.log(_1_array_1.maxOfArray([1, 3, 58, 32, 67]));
console.log(_2_vocale_conso_1.isVowel("1"));
console.log(_3_inverse_1.inverseOfString("ZiboCuju"));
console.log(_4_pali_1.isPalindrome("I topi non avevano nipoti"));
console.log(_5_factorial_1.factorial(4));
console.log(_6_vectorprod_1.vectorZipByRecursion([1, 2, 3], [4, 5]));
